updated publish tool

diff --git a/tool/publish b/tool/publish
--- a/tool/publish
+++ b/tool/publish
@@ -1,6 +1,16 @@
 #!/bin/bash
 set -e
 
+function evil_git_dirty {
+  return $(git diff --shortstat 2> /dev/null | tail -n1) != "";
+}
+
+if [ evil_git_dirty ]
+then
+      echo 'ERROR: git repo is not clean';
+      exit 1;
+fi
+
 target=( rmi rmi_generator )
 resource=( README.md LICENSE example CHANGELOG.md )
 for i in "${target[@]}"
@@ -10,3 +20,12 @@ do
             cp -r $j $i 
       done       
 done 
+
+cd rmi;
+pub publish;
+cd ..;
+cd rmi_generator;
+pub publish;
+cd ..;
+
+git clean -f -d
